### ISSUE TITLE
affected wiil trigger build to the host, but it's not needed

### ISSUE THREAD

**Issue by gilamran** [nrwl/react-module-federation#4]
hi,
After running a build, changing one file of the `about-main` lib, and then running `nx affected:graph` we see that the `host` is marked as affected, even that it's not required to be built. The host will load the `about-main` at run time and does not need to be recompiled.
The recompilation of the host is caused by the `"implicitDependencies": ["cart", "shop", "about"]` inside `project.json` in the host. removing it will not require building the host.

Am I missing something here?

Thanks

**Comment by juristr** [comment]
Hey, this is purely an example repo. Can you reach out either

- on our [community slack](https://go.nrwl.io/join-slack)
- open an issue [on GitHub](https://github.com/nrwl/nx/issues)
 
Best is probably to first ask in the community slack and in case we can open an issue from there. Feel also free to tag me there, so I see it quickly

Thanks a lot for reaching out 🙏
